const services = [
    {
        name: 'auth',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3000,
    },
    {
        name: 'weather',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3001,
    },
    {
        name: 'routes',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3002,
    },
    {
        name: 'places',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3003,
    },
    {
        name: 'travel',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3004,
    },
    {
        name: 'community',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3005,
    },
    {
        name: 'support',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3006,
    },
    {
        name: 'reviews',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3007,
    },
    {
        name: 'user',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3008,
    },
    {
        name: 'dwelling',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3009,
    },
    {
        name: 'search',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3010,
    },
    {
        name: 'recommendation',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3011,
    },
    {
        name: 'notification',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3012,
    },
    {
        name: 'transport',
        protocol: 'http',
        host: '127.0.0.1',
        docker_host: 'host.docker.internal',
        port: 3013,
    }
]

module.exports = services;