const services = [
    {
        name: 'auth',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'auth-middleware-container',
        docker_dev_host: 'host.docker.internal',
        port: 3000,
    },
    {
        name: 'weather',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'weather-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3001,
    },
    {
        name: 'routes',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'routes-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3002,
    },
    {
        name: 'places',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'places-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3003,
    },
    {
        name: 'travels',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'travels-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3004,
    },
    {
        name: 'community',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'community-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3005,
    },
    {
        name: 'support',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'support-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3006,
    },
    {
        name: 'reviews',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'reviews-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3007,
    },
    {
        name: 'user',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'user-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3008,
    },
    {
        name: 'dwelling',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'dwelling-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3009,
    },
    {
        name: 'search',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'search-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3010,
    },
    {
        name: 'recommendation',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'recommendation-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3011,
    },
    {
        name: 'notification',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'notification-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3012,
    },
    {
        name: 'transport',
        protocol: 'http',
        localhost: '127.0.0.1',
        dns_host: 'transport-service-container',
        docker_dev_host: 'host.docker.internal',
        port: 3013,
    }
]

module.exports = services;